# Generated by Django 3.2.7 on 2021-09-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=120, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('endereco', models.CharField(max_length=120, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Hóspede',
                'verbose_name_plural': 'Hóspedes',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de', models.DateField(verbose_name='Data - Entrada')),
                ('data_ate', models.DateField(verbose_name='Data - Saída')),
                ('qtd_pessoas_adulto', models.IntegerField(verbose_name='Qtd. Adultos')),
                ('qtd_pessoas_crianca', models.IntegerField(verbose_name='Qtd. Crianças')),
                ('pago', models.CharField(choices=[('false', 'Não'), ('true', 'Sim'), ('partial', 'Parcial')], max_length=10)),
                ('valor', models.FloatField()),
                ('hospede', models.ManyToManyField(to='reserva.Hospede')),
            ],
        ),
    ]
