# Generated by Django 3.2.7 on 2021-09-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospede', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(verbose_name='Data - Entrada')),
                ('data_saida', models.DateField(verbose_name='Data - Saída')),
                ('qtd_pessoas_adulto', models.PositiveIntegerField(verbose_name='Qtd. Adultos')),
                ('qtd_pessoas_crianca', models.PositiveIntegerField(verbose_name='Qtd. Crianças')),
                ('pago', models.CharField(choices=[('false', 'Não'), ('true', 'Sim'), ('partial', 'Parcial')], max_length=10)),
                ('valor_pago_total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor total')),
                ('valor_pago_parcial', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor adiantado')),
                ('pagara_limpeza', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Pagará limpeza?')),
                ('payed_limpeza', models.BooleanField(default=False, editable=False)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospede.hospede', verbose_name='Hóspede')),
            ],
        ),
    ]
