# Generated by Django 3.2.7 on 2021-09-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospede', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de', models.DateField(verbose_name='Data - Entrada')),
                ('data_ate', models.DateField(verbose_name='Data - Saída')),
                ('qtd_pessoas_adulto', models.PositiveIntegerField(verbose_name='Qtd. Adultos')),
                ('qtd_pessoas_crianca', models.PositiveIntegerField(verbose_name='Qtd. Crianças')),
                ('pago', models.CharField(choices=[('false', 'Não'), ('true', 'Sim'), ('partial', 'Parcial')], max_length=10)),
                ('valor', models.FloatField()),
                ('hospede', models.ManyToManyField(to='hospede.Hospede')),
            ],
        ),
    ]
