# Generated by Django 3.2.7 on 2021-09-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_entrada',
            field=models.DateTimeField(verbose_name='Data - Entrada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_saida',
            field=models.DateTimeField(verbose_name='Data - Saída'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pagara_limpeza',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Incluir limpeza?'),
        ),
    ]
