# Generated by Django 3.2.7 on 2021-09-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospede', '0001_initial'),
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospede',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hospede',
            field=models.ManyToManyField(to='hospede.Hospede'),
        ),
    ]
