# Generated by Django 3.2.7 on 2021-10-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=120, verbose_name='Endereço')),
                ('avaliacao', models.IntegerField(blank=True, choices=[(0, 'Ótimo'), (1, 'Bom'), (2, 'Regular'), (3, 'Ruim'), (4, 'Péssimo')], null=True, verbose_name='Avaliação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hóspede',
                'verbose_name_plural': 'Hóspedes',
            },
        ),
    ]
